### ISSUE TITLE
change Gatsby-node.js

### ISSUE THREAD

**Issue by tanya044** [gatsbyjs/gatsby-fr#55]
title: The gatsby-node.js API file
 ---

 Le code du fichier `gatsby-node.js` est exécuté une fois dans le processus de création de votre site. Vous pouvez l'utiliser pour créer des pages de manière dynamique, ajouter des nœuds dans GraphQL ou répondre à des événements pendant le cycle de vie de la construction. Pour utiliser les [API Gatsby Node] (/docs/node-apis/), créez un fichier nommé `gatsby-node.js` à la racine de votre site. Exportez l'une des API que vous souhaitez utiliser dans ce fichier.
 Le code du fichier `gatsby-node.js` est exécuté une fois dans le processus de création de votre site. Vous pouvez l'utiliser pour créer des pages de manière dynamique, ajouter des nœuds dans GraphQL ou répondre à des événements pendant le cycle de vie de la construction. Pour utiliser les [APIs Gatsby Node] (/docs/node-apis/), créez un fichier nommé `gatsby-node.js` à la racine de votre site. Exportez l'une des API que vous souhaitez utiliser dans ce fichier.

 Chaque API Gatsby Node transmet un [ensemble d'assistants API Node] (/docs/node-api-helpers/). Ceux-ci vous permettent d'accéder à plusieurs méthodes telles que la rapport ou d'effectuer des actions telles que la création de nouvelles pages.

**Comment by SamuelAlev** [comment]
Salut,
Merci pour ta traduction ! Néanmoins le fichier a déjà été traduit (voir #54).
Tu peux choisir un autre fichier mais fait attention qu'il ne soit pas déjà pris ;)
Concernant les traductions, seules les PR sont prises en compte.
